// Command matrix prints the conversion matrix as Markdown, generated from
// the catalogue and the edge table so README never drifts from the code:
//
//	go run ./tools/matrix > MATRIX.md
package main

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/brf-tech/filex-convert/internal/formats"
	"github.com/brf-tech/filex-convert/internal/graph"
)

// notOffered lists the conversions the old browser converter (or a user)
// might expect and this plugin deliberately does not promise, with the
// reason. It is kept here so MATRIX.md regenerates with it.
var notOffered = [][2]string{
	{"PDF → DOCX / ODT / RTF (editable text with layout)", "no engine path: the office engine is asked for office documents only, and a PDF turned into one is a page of text boxes, not a document. The text itself is reachable: PDF → TXT (poppler or Ghostscript)."},
	{"EPUB → anything through pandoc", "pandoc is not one of the six host engines; EPUB is read by the sandbox's own reader instead (text, structure, tables) and written by its own writer."},
	{"MOBI / AZW3", "proprietary Kindle containers; no reader or writer in pure Go within the size budget and no engine handles them. Convert the EPUB instead."},
	{"7z", "the pure-Go reader costs 5.4 MiB of wasm (measured with `scripts/size-probe.sh`), which would push the module past the 16 MiB gate. RAR is read; 7z is not."},
	{"RAR / 7z / tar.bz2 writing", "RAR's compressor is proprietary, 7z is not read either, and Go's standard library has no bzip2 compressor. Every archive can be read into ZIP, TAR, tar.gz, tar.zst or tar.xz."},
	{"WOFF2", "needs Brotli plus the glyf transform; WOFF 1.0 is exact and round-trips, WOFF2 is not offered."},
	{"OTF (CFF outlines) → TTF", "the outlines would have to be converted from cubic to quadratic curves; renaming would produce a broken font. TTF → OTF is offered (an OpenType file may carry TrueType outlines)."},
	{"HEIC / AVIF / DDS / EXR / XCF / PSD *writing* without ImageMagick", "no pure-Go encoders exist for HEIF, and PSD/XCF writers make little sense for a converter; with ImageMagick, PSD, DDS, EXR and AVIF are written. HEIC writing needs libheif, which even ImageMagick builds rarely carry - not offered."},
	{"Animated PNG / WebP decoding in pure Go", "Go's codecs read one frame; animated conversions run through ffmpeg."},
	{"SVG rasterising without an engine", "an SVG renderer is a browser engine; SVG → PNG/PDF needs rsvg or ImageMagick. The other direction (raster → SVG) wraps the bitmap; it is not a vector trace."},
	{"Image → vector trace (potrace)", "not offered; raster → SVG embeds the bitmap."},
	{"OCR (image / scanned PDF → text)", "no OCR engine on the host; PDF → TXT extracts the text layer only."},
	{"Text → speech, MIDI, trackers, game and 3D formats, source-code transpilers, SQLite dumps", "outside the scope of a file converter for documents, media, data and archives; the old converter's niche handlers are not replicated."},
	{"Video → subtitles (speech recognition)", "no engine for it; subtitle tracks are not extracted either (ffmpeg could, but a stream index knob is not exposed in this version)."},
	{"XLSX / ODS with several sheets", "only the first sheet is read; XLSX is written as one sheet. Formulas are read as their cached values; dates come out as serial numbers."},
	{"DOC (Word 97) / PPT / XLS binary formats without the office engine", "the binary Office formats have no pure-Go reader here; the office engine (the connected ONLYOFFICE) converts them."},
}

func main() {
	w := os.Stdout
	edges := graph.Edges()
	packs := 0
	for _, e := range edges {
		if graph.IsPack(e) {
			packs++
		}
	}
	fmt.Fprintln(w, "# Conversion matrix")
	fmt.Fprintln(w)
	fmt.Fprintf(w, "Generated by `go run ./tools/matrix` from the edge table: %d formats in %d categories, %d direct edges (%d of them \"pack this file into an archive\", listed once below rather than per cell). ", len(formats.All), len(formats.Categories), len(edges), packs)
	fmt.Fprintln(w, "A cell names the engine of the cheapest *direct* edge; routes may chain up to three edges (README explains the planner), so a blank cell is not always \"impossible\" - `docx → png` goes `docx → pdf → png`. `go` = pure Go inside the sandbox, no engine needed; `*` = lossy (re-encoding, rasterising, structure dropped).")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "This is the parity target against the old browser converter: everything it offered for images, video, audio, documents, e-books, archives, data, subtitles and fonts is either a cell here or a row under [Not offered](#not-offered), with the reason.")
	fmt.Fprintln(w)

	for _, c := range formats.Categories {
		sources := formats.InCategory(c)
		targetSet := map[string]bool{}
		for _, s := range sources {
			for _, e := range edges {
				if e.From == s.ID && !graph.IsPack(e) {
					targetSet[e.To] = true
				}
			}
		}
		if len(targetSet) == 0 {
			continue
		}
		var targets []*formats.Format
		for _, tc := range formats.Categories {
			for _, f := range formats.InCategory(tc) {
				if targetSet[f.ID] {
					targets = append(targets, f)
				}
			}
		}
		fmt.Fprintf(w, "## %s → …\n\n", formats.CategoryLabel(c)["en"])
		fmt.Fprint(w, "| from \\ to |")
		for _, t := range targets {
			fmt.Fprintf(w, " %s |", t.ID)
		}
		fmt.Fprintln(w)
		fmt.Fprint(w, "|---|")
		for range targets {
			fmt.Fprint(w, "---|")
		}
		fmt.Fprintln(w)
		for _, s := range sources {
			fmt.Fprintf(w, "| **%s** |", s.ID)
			for _, t := range targets {
				fmt.Fprintf(w, " %s |", cell(s.ID, t.ID))
			}
			fmt.Fprintln(w)
		}
		fmt.Fprintln(w)
	}

	fmt.Fprintln(w, "## Any file → archive")
	fmt.Fprintln(w)
	fmt.Fprintf(w, "Every non-archive format has a pure-Go edge to %s: the file is packed as the archive's single member, named after the source. With several files selected and **Combine into one file** on, the selection becomes one archive (see README, *Merge*).\n", strings.Join(graph.ArchiveWritable, ", "))
	fmt.Fprintln(w)

	fmt.Fprintln(w, "## Not offered")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "| Conversion | Why |")
	fmt.Fprintln(w, "|---|---|")
	for _, n := range notOffered {
		fmt.Fprintf(w, "| %s | %s |\n", n[0], n[1])
	}
	fmt.Fprintln(w)

	fmt.Fprintln(w, "## Options per edge")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "| edge | engine | lossy | options |")
	fmt.Fprintln(w, "|---|---|---|---|")
	sort.Slice(edges, func(i, j int) bool { return edges[i].Key() < edges[j].Key() })
	for _, e := range edges {
		if len(e.Options) == 0 {
			continue
		}
		eng := e.Engine
		if eng == "" {
			eng = "go"
		}
		fmt.Fprintf(w, "| %s → %s | %s | %v | %s |\n", e.From, e.To, eng, e.Lossy, strings.Join(e.Options, ", "))
	}
}

func cell(from, to string) string {
	var best *graph.Edge
	for _, e := range graph.Direct(from, to) {
		e := e
		if graph.IsPack(e) {
			continue
		}
		if best == nil || e.Weight() < best.Weight() {
			best = &e
		}
	}
	if best == nil {
		return ""
	}
	name := best.Engine
	if name == "" {
		name = "go"
	}
	if best.Lossy {
		name += "*"
	}
	return name
}
